In [32]:
import pandas as pd
from unidecode import unidecode
import numpy as np

In [33]:
redd = pd.read_csv('casual_conversations.csv', low_memory=False)

In [34]:

all_text = pd.concat([redd.text_1, redd.text_2, redd.text_3])
all_text.info()

<class 'pandas.core.series.Series'>
Int64Index: 168891 entries, 0 to 56296
Series name: None
Non-Null Count   Dtype
--------------   -----
168891 non-null  object
dtypes: object(1)
memory usage: 2.6+ MB

In [35]:
# there's no NA entries so dropna doesn't do anything 
# redd = redd.dropna()
# redd.info()

In [36]:
# get rid of duplicates
all_text = all_text.drop_duplicates()

In [37]:
# take out just the first column of texts, remove emojis
# the resulting variable is a series, with the origianl index and the first column in the file
# when accessing, can use [n], result is a string
all_text = all_text.apply(unidecode)

In [38]:
def remove_subredd(text):
    return ' '.join([t for t in text.split() if t.find('/r') == -1])

all_text = all_text.apply(remove_subredd)

In [39]:
def remove_subredd2(text):
    return ' '.join([t for t in text.split() if t.find('r/') == -1])

all_text = all_text.apply(remove_subredd2)

In [40]:
def remove_name(text):
    return ' '.join([t for t in text.split() if t.find('/u') == -1])

all_text = all_text.apply(remove_name)

In [41]:
all_text = all_text.apply(lambda x: x.replace('\n', ' ').replace('&gt', '').replace('&lt', '').replace('\'', "'")
                           ) # get rid of \n, >, <

In [42]:
all_text.info()

<class 'pandas.core.series.Series'>
Int64Index: 72534 entries, 0 to 56296
Series name: None
Non-Null Count  Dtype
--------------  -----
72534 non-null  object
dtypes: object(1)
memory usage: 1.1+ MB

In [47]:
# checking how it looks 
for i in range(len(all_text)):
    
    if all_text.iloc[i].strip() == '':
        all_text.iloc[i] = np.nan;
        #print(all_text.iloc[i])
        
all_text.info()

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
<class 'pandas.core.series.Series'>
Int64Index: 72534 entries, 0 to 56296
Series name: None
Non-Null Count  Dtype
--------------  -----
72135 non-null  object
dtypes: object(1)
memory usage: 1.1+ MB

In [48]:
# clean up the newly created empty 
all_text = all_text.dropna()
all_text.info()

<class 'pandas.core.series.Series'>
Int64Index: 72135 entries, 0 to 56296
Series name: None
Non-Null Count  Dtype
--------------  -----
72135 non-null  object
dtypes: object(1)
memory usage: 1.1+ MB

In [49]:
all_text.to_csv('cleaned_reddict_convo.csv')