In [1]:
import pandas as pd

In [2]:
pwd

'/home/azizbg/Desktop/cautious-octo-train/cautious-octo-train/instagram_data'

In [3]:
df = pd.read_csv('insta.csv')

In [4]:
df

,Caption,Instagram,YouTube,Twitter
0,bye,1,0,0
1,"Ok, a few more... sorry I just had so much fun...",1,0,0
2,This was one of my favorite shoots I've ever d...,1,0,0
3,Wrapped round my finger like a ring,1,0,0
4,Yesterday was so much fun!! has been such a hu...,1,0,0
...,...,...,...,...
15647,Kramer!,1,0,0
15648,Cowgirl :),1,0,0
15649,I love me and Kylie's nail polish colors!,1,0,0
15650,Fammm,1,0,0
15651,Disneyland!,1,0,0

In [8]:
import re

def removingat(string):
    return re.sub('@[\w]+','',string)

def removingdash(string):
    return re.sub('#[\w]+','',string)

In [9]:
df['Caption'] = df['Caption'].apply(removingat)

In [10]:
df['Caption'] = df['Caption'].apply(removingdash)

In [11]:
df

,Caption,Instagram,YouTube,Twitter
0,bye,1,0,0
1,"Ok, a few more... sorry I just had so much fun...",1,0,0
2,This was one of my favorite shoots I've ever d...,1,0,0
3,Wrapped round my finger like a ring,1,0,0
4,Yesterday was so much fun!! has been such a hu...,1,0,0
...,...,...,...,...
15647,Kramer!,1,0,0
15648,Cowgirl :),1,0,0
15649,I love me and Kylie's nail polish colors!,1,0,0
15650,Fammm,1,0,0
15651,Disneyland!,1,0,0

In [12]:
df.to_csv('insta_clean.csv', index=False)